apiVersion: v1
kind: Service
metadata:
  name: storybook
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 6006
  selector:
    app: storybook
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
  selector:
    app: react-app